# **TUGAS NUMPY 2026** 🧮

---
**Nama:**  Sheyla Natasha Rahma Ditia

**NIM:**  245150401111016

Notebook ini berisi penugasan **NumPy** sebagai latihan lanjutan setelah workshop.

### Aturan singkat
- Kerjakan mandiri.
- Gunakan **NumPy** sebagai alat utama.
- Untuk soal yang berkaitan dengan masking, broadcasting, dan reshaping, usahakan **tidak menggunakan loop** jika memang bisa diselesaikan dengan operasi NumPy.
- Tulis jawaban langsung di cell yang sudah disediakan.


## **📦 Import Library**

Jalankan cell berikut terlebih dahulu.


In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 4.3 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.3 MB 7.1 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.3 MB 8.0 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.3 MB 8.5 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.3 MB 8.7 MB/s eta 0:00:01
   --------------------------- ------------ 8.4/12.3 MB 8.3 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 7.0 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 6.6 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# Seed supaya hasil random konsisten
rng = np.random.default_rng(42)


## **📌 Soal 1: Membuat Array & Membaca Informasinya**

Buatlah array NumPy bernama `scores` dengan isi nilai berikut:

`[78, 85, 90, 66, 74, 88, 92, 81]`

Lalu tampilkan:
1. Isi array
2. Jumlah dimensi
3. Shape
4. Banyak elemen
5. Tipe data

**Hint:** gunakan `np.array`, lalu cek `ndim`, `shape`, `size`, dan `dtype`.


In [7]:
# Tulis jawabanmu di sini
a = np.array([78, 85, 90, 66, 74, 88, 92, 81])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[78 85 90 66 74 88 92 81]
1
(8,)
8
int64


## **📌 Soal 2: Factory Functions**

Gunakan fungsi bawaan NumPy untuk membuat:
1. Array `A` berukuran `3x4` yang seluruh elemennya `0`
2. Array `B` berukuran `2x3` yang seluruh elemennya `1`
3. Array `C` berukuran `3x3` yang seluruh elemennya `7`
4. Matriks identitas `D` berukuran `4x4`
5. Array `E` yang berisi 6 angka dari `0` sampai `1` dengan jarak sama rata

Tampilkan semua hasilnya.


In [18]:
# Tulis jawabanmu di sini
a = np.zeros((3,4))
b = np.ones((2,3))
c = np.full((3,3),7)
d = np.eye((4))
e = np.linspace(0,1,6)
print("Array A")
print(a)
print("Array B")
print(b)
print("Array C")
print(c)
print("Array D")
print(d)
print("Array E")
print(e)

Array A
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array B
[[1. 1. 1.]
 [1. 1. 1.]]
Array C
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Array D
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array E
[0.  0.2 0.4 0.6 0.8 1. ]


## **📌 Soal 3: Indexing & Slicing**

Perhatikan array berikut:


In [19]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Dari array tersebut, tampilkan:
1. Elemen pada baris ke-2 kolom ke-3
2. Seluruh baris pertama
3. Seluruh kolom terakhir
4. Subarray 2x2 di tengah
5. Array hasil membalik urutan kolom pada semua baris

**Catatan:** gunakan indexing/slicing NumPy.


In [41]:
# Tulis jawabanmu di sini
print(arr[2,3])
print(arr[0])
print(arr[:,3])
print(arr[[1,2],1:3])
print(arr[:,-1:-5:-1])

12
[1 2 3 4]
[ 4  8 12 16]
[[ 6  7]
 [10 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


## **📌 Soal 4: Boolean Masking & `np.where()`**

Diberikan array suhu berikut:


In [42]:
temps = np.array([29, 31, 35, 28, 33, 27, 30, 36, 32, 26])
print(temps)


[29 31 35 28 33 27 30 36 32 26]


Kerjakan hal berikut:
1. Ambil semua suhu yang **lebih dari 30**
2. Hitung berapa banyak suhu yang **lebih dari atau sama dengan 32**
3. Buat array label baru bernama `status` dengan aturan:
   - `"panas"` jika suhu > 32
   - `"normal"` jika suhu 29 s.d. 32
   - `"dingin"` jika suhu < 29

**Hint:** untuk poin (3), kamu bisa menggunakan `np.where()` bertingkat.


In [48]:
# Tulis jawabanmu di sini
print(temps[temps>30])
print(len(temps[temps>=32]))
print(np.where(temps>32,"panas", np.where(temps<29,"dingin","normal")))

[31 35 33 36 32]
4
['normal' 'normal' 'panas' 'dingin' 'panas' 'dingin' 'normal' 'panas'
 'normal' 'dingin']


## **📌 Soal 5: View vs Copy**

Buat array berikut:


In [49]:
x = np.array([10, 20, 30, 40, 50, 60])
print(x)


[10 20 30 40 50 60]


Lalu lakukan:
1. Buat `view_part` dari elemen indeks 1 sampai 4 menggunakan slicing
2. Buat `copy_part` dari elemen indeks `[1, 2, 3, 4]` menggunakan advanced indexing
3. Ubah elemen pertama `view_part` menjadi `999`
4. Ubah elemen pertama `copy_part` menjadi `-100`
5. Tampilkan `x`, `view_part`, dan `copy_part`

Terakhir, tuliskan dengan singkat:
- mana yang menyebabkan array asli berubah?
- mana yang tidak?


In [ ]:
# Tulis jawabanmu di sini
# Tambahkan penjelasan singkat dalam komentar juga.
view_part = x[1:4]
copy_part = x[[1,2,3,4]]
view_part[0] = 999 #mengubah array asli
copy_part[0] = -100 #tidak mengubah array asli, tapi mengubah diri sendiri
print(x) #index 1 berubah menjadi 999 akibat view_part
print(view_part) #index 0 berubah menjadi 999
print(copy_part) #index 0 berubah menjadi -100

[ 10 999  30  40  50  60]
[999  30  40]
[-100   30   40   50]


## **📌 Soal 6: Statistik Dasar & Missing Value (`NaN`)**

Gunakan array berikut:


In [52]:
values = np.array([12, 15, np.nan, 18, 21, np.nan, 24, 30])
print(values)


[12. 15. nan 18. 21. nan 24. 30.]


Tampilkan:
1. Rata-rata biasa dengan `np.mean()`
2. Rata-rata yang mengabaikan `NaN` dengan `np.nanmean()`
3. Standar deviasi yang mengabaikan `NaN` dengan `np.nanstd()`
4. Nilai minimum dan maksimum yang mengabaikan `NaN`

Lalu jelaskan singkat kenapa hasil `np.mean()` bisa berbeda dari `np.nanmean()`.


In [56]:
# Tulis jawabanmu di sini
print(f"mean with nan: {np.mean(values)}") # tidak bisa menghitung rata-rata apabila masih ada nan dalam array
print(f"mean w/o nan: {np.nanmean(values)}") # menghitung rata-rata dengan menjumlahkan elemen bukan nan dan membagi dengan jumlah elemen bukan nan -> 120/60 = 20
print(f"standar deviasi w/o nan: {np.nanstd(values)}")
print(f"min: {np.nanmin(values)} max: {np.nanmax(values)}")

mean with nan: nan
mean w/o nan: 20.0
standar deviasi w/o nan: 5.916079783099616
min: 12.0 max: 30.0


## **📌 Soal 7: Broadcasting untuk Normalisasi**

Diberikan matriks fitur berikut:


In [ ]:
X = np.array([
    [170, 65, 28],
    [165, 55, 24],
    [180, 75, 30],
    [175, 70, 29]
], dtype=float)

print(X)

[[170.  65.  28.]
 [165.  55.  24.]
 [180.  75.  30.]
 [175.  70.  29.]]
(6,)


Anggap setiap kolom merepresentasikan fitur yang berbeda.  
Lakukan normalisasi z-score sederhana dengan rumus:

$$
Z = \frac{X - \text{mean kolom}}{\text{std kolom}}
$$

Tampilkan:
1. Mean per kolom
2. Std per kolom
3. Hasil normalisasi `Z`

**Hint:** gunakan `axis=0` dan manfaatkan broadcasting NumPy.


In [81]:
# Tulis jawabanmu di sini
mean = np.mean(X, axis=0).shape
mean
std = np.std(X, axis=0)
Z = (X-mean)/std
print(f"mean per kolom: {mean}")
print(f"std per kolom: {std}")
print(f"hasil normalisasi Z: {Z}")


mean per kolom: (3,)
std per kolom: [5.59016994 7.39509973 2.27760839]
hasil normalisasi Z: [[29.87386818  8.38393021 10.976426  ]
 [28.97944099  7.0316834   9.22019784]
 [31.66272256  9.73617701 11.85454008]
 [30.76829537  9.06005361 11.41548304]]


## **📌 Soal 8: Reshape & Mini Challenge**

Gunakan array 1 dimensi berikut:


In [3]:
z = np.arange(1, 25)
print(z)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


Kerjakan hal berikut:
1. Ubah `z` menjadi matriks berukuran `6x4`
2. Ubah hasilnya menjadi bentuk `3x2x4`
3. Ambil kembali seluruh data tersebut menjadi array 1 dimensi
4. Bonus: buat array window 4 elemen yang bergeser dari `z`, sehingga bentuk akhirnya menjadi:

`[[1,2,3,4], [2,3,4,5], ..., [21,22,23,24]]`

**Hint bonus:** boleh gunakan loop **atau** `sliding_window_view` jika kamu sudah tahu.


In [15]:
# Tulis jawabanmu di sini
z = z.reshape(6,4)
print(z)
z = z.reshape(3,2,4)
print(z)
z= z.reshape(24,)
print(z)

bonus = []
for i in range(22):
    window = z[i:i+3]
    bonus.append(window)

bonus = np.array(bonus)
print(bonus)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]
 [18 19 20]
 [19 20 21]
 [20 21 22]
 [21 22 23]
 [22 23 24]]


# **🎯 Penutup**

Kalau kamu sudah menyelesaikan semua soal:
- cek lagi hasil outputmu,
- pastikan bentuk array dan logikanya sesuai,
- lalu simpan notebook ini sebelum dikumpulkan.

Semangat! 🚀
